name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Install gtk
      run: sudo apt-get install libgtk-3-dev libcairo2-dev libglib2.0-dev
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Build
      run: make install && make build

    - name: Test
      run: ./GoTeach.out
